resources:
- name: online-systems
  type: git
  source:
    uri: https://github.com/mmochan/ansible-test
    branch: master

jobs:
- name: VPC
  plan:
  - get: online-systems
    trigger: true    
  - task: tests
    file: ansible-test/build.yml
- name: Virtual Private Gateways
  plan:
  - get: online-systems
    trigger: true    
  - task: tests
    file: ansible-test/build.yml    
- name: Customer Gateways
  plan:
  - get: online-systems
    trigger: true    
  - task: tests
    file: ansible-test/build.yml        
- name: VPC Endpoints
  plan:
  - get: online-systems
    trigger: true    
  - task: tests
    file: ansible-test/build.yml    
- name: Subnets
  plan:
  - get: online-systems
    trigger: true    
  - task: tests
    file: ansible-test/build.yml    
- name: Peering Connections
  plan:
  - get: online-systems
    trigger: true    
  - task: tests
    file: ansible-test/build.yml       
- name: Network ACLS
  plan:
  - get: online-systems
    trigger: true    
  - task: tests
    file: ansible-test/build.yml   
- name: Route Tables
  plan:
  - get: online-systems
    trigger: true    
  - task: tests
    file: ansible-test/build.yml       
- name: Security Groups
  plan:
  - get: online-systems
    trigger: true    
  - task: tests
    file: ansible-test/build.yml             

